
```{r criando funções}
# Função para converter todas as colunas para o tipo character
convert_to_character <- function(df) {
  df[] <- lapply(df, as.character)
  return(df)
}

###########################################################################

# Função para normalizar os nomes das colunas
library(stringr)
normalize_column_names <- function(df) {
  # Remover acentuação
  colnames(df) <- iconv(colnames(df), from = "UTF-8", to = "ASCII//TRANSLIT")
  # Converter para minúsculas
  colnames(df) <- tolower(colnames(df))
  # Substituir espaços por underscores
  colnames(df) <- str_replace_all(colnames(df), " ", "_")
  # Remover caracteres especiais, mantendo apenas letras, números e underscores
  colnames(df) <- gsub("[^a-z0-9_]", "", colnames(df))
  # Substituir múltiplos underscores consecutivos por um único underscore
  colnames(df) <- gsub("_+", "_", colnames(df))
  # Remover underscores no início ou fim dos nomes de colunas
  colnames(df) <- gsub("^_|_$", "", colnames(df))
  
  return(df)
}

normalize_vector_names <- function(v) {
  # Remover acentuação
  v <- iconv(v, from = "UTF-8", to = "ASCII//TRANSLIT")
  # Converter para minúsculas
  v <- tolower(v)
  # Substituir espaços por underscores
  v <- str_replace_all(v, " ", "_")
  # Remover caracteres especiais, mantendo apenas letras, números e underscores
  v <- gsub("[^a-z0-9_]", "", v)
  # Substituir múltiplos underscores consecutivos por um único underscore
  v <- gsub("_+", "_", v)
  # Remover underscores no início ou fim dos nomes
  v <- gsub("^_|_$", "", v)
  
  return(v)
}
```

```{r}

library(arrow)
df = read_parquet("C:/Users/gabri/OneDrive/Documentos/Criptos/RoboTraderBinance_1_4b/src/tests/graficos/DADOS_SIMULADOS_1semana_1h_definitivos.parquet")
df = normalize_column_names(df)
df = df %>% mutate(moeda_estrategia = paste0(moeda, '\n', estrategia))

df %>% dim()

# df %>% View()
df %>% names()

df_bck = df
```

```{r}
df$trade_01 = ifelse(df$total_trades >= 1, 1, 0)
table(df$estrategia, df$trade_01) %>% capture()
conti(df, 'trade_01', 'data_inicio')
conti(df, 'trade_01', 'estrategia', 'row')
df = df %>% filter(trade_01 == 1)
df
```

```{r}
# df$estrategia %>% table()
# df$moeda %>% table()
```

```{r}
df %>% filter(moeda == 'TRX')
```


# ANALISE BI VARIADA


```{r}
arredondamento = 1
```

```{r MOEDA}
medidas <- df %>%
  group_by(moeda) %>%
  summarise(
    min = round(min(lucro, na.rm = TRUE), arredondamento),
    media = round(mean(lucro, na.rm = TRUE), arredondamento),
    desv_pad = round(sd(lucro, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    max = round(max(lucro, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>%
  mutate(classificacao = ifelse(mediana <= 0, "Negativa", "Positiva") %>% as.factor()) %>% 
  arrange(-mediana) %>% filter(classificacao == "Positiva")
medidas

p <- ggplot(df %>% filter(moeda %in% medidas$moeda), 
            aes(x = as.factor(moeda), y = lucro, fill = as.factor(moeda))) + 
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE, width = 0.5) +
  # Médias extras
  geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = NULL, fill= NULL) +
  coord_flip()

p %>% print()
```

```{r ESTRATEGIA}
medidas <- df %>%
  group_by(estrategia) %>%
  summarise(
    min = round(min(lucro, na.rm = TRUE), arredondamento),
    media = round(mean(lucro, na.rm = TRUE), arredondamento),
    desv_pad = round(sd(lucro, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    max = round(max(lucro, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>%
  mutate(classificacao = ifelse(mediana <= 0, "Negativa", "Positiva") %>% as.factor()) %>% 
  arrange(-mediana) %>% filter(classificacao == "Positiva")
medidas

p <- ggplot(df %>% filter(estrategia %in% medidas$estrategia), 
            aes(x = as.factor(estrategia), y = lucro, fill = as.factor(estrategia))) + 
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE, width = 0.5) +
  # Médias extras
  geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = NULL) +
  coord_flip()

p %>% print()
```

# ANALISE MULTI VARIADA

```{r Combinação estrategia moeda que mais deram certo ?}
medidas <- df %>%
  group_by(estrategia, moeda) %>%
  summarise(
    n = n(),
    min = round(min(lucro, na.rm = TRUE), arredondamento),
    # media = round(mean(lucro, na.rm = TRUE), arredondamento),
    # desv_pad = round(sd(lucro, na.rm = TRUE), arredondamento),
    P12_5 = round(quantile(lucro, probs = 0.125, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    max = round(max(lucro, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>% 
  mutate(moeda_estrategia = paste0(moeda, '\n', estrategia),
         exibir = paste0(moeda_estrategia, 'n=', n)) %>% 
  filter(Q1 != mediana & mediana != Q3) %>% 
  filter(n >= 10)
medidas

# Analise mediana -----------------------------------------------------------------------------
melhores_medianas = medidas %>%
  mutate(classificacao = ifelse(mediana <= 0, "Negativa", "Positiva") %>% as.factor()) %>% 
  arrange(-mediana) %>% filter(classificacao == "Positiva") %>% 
  slice(1:40)
melhores_medianas

p <- ggplot(df %>% filter(moeda_estrategia %in% melhores_medianas$moeda_estrategia), 
            aes(x = factor(moeda_estrategia, levels = melhores_medianas$moeda_estrategia),
                y = lucro,
                fill = factor(moeda_estrategia, levels = melhores_medianas$moeda_estrategia))) +
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = TRUE, width = 0.5) +
  # Médias extras
  # geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "none") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = 'melhores medianas', fill = NULL) +
  coord_flip() + 
  scale_y_continuous(breaks = seq(floor(min(df$lucro, na.rm = TRUE)),
                                  ceiling(max(df$lucro, na.rm = TRUE)),
                                  by = 2))
p %>% print()
ggsave("melhores medianas.jpg", height = 40, width = 25, units = "cm", dpi = 600)

# Analise Q1 -----------------------------------------------------------------------------
melhores_Q1 = medidas %>%
  mutate(classificacao = ifelse(Q1 <= 0, "Negativa", "Positiva") %>% as.factor()) %>% 
  arrange(-Q1, -P12_5) %>% filter(classificacao == "Positiva") #%>% 
  # slice(1:20)
melhores_Q1

p <- ggplot(df %>% filter(moeda_estrategia %in% melhores_Q1$moeda_estrategia), 
            aes(x = factor(moeda_estrategia, levels = melhores_Q1$moeda_estrategia),
                y = lucro,
                fill = factor(moeda_estrategia, levels = melhores_Q1$moeda_estrategia) ) ) +
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = TRUE, width = 0.5) +
  # Médias extras
  # geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "none") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = 'melhores q1', fill = NULL) +
  coord_flip() + 
  scale_y_continuous(breaks = seq(floor(min(df$lucro, na.rm = TRUE)),
                                  ceiling(max(df$lucro, na.rm = TRUE)),
                                  by = 2))

p %>% print()
ggsave("melhores q1.jpg", height = 40, width = 25, units = "cm", dpi = 600)

# Analise p12.5 -----------------------------------------------------------------------------
melhores_p12_5 = medidas %>%
  mutate(classificacao = ifelse(P12_5 <= 0, "Negativa", "Positiva") %>% as.factor()) %>% 
  arrange(-P12_5) %>% filter(classificacao == "Positiva") %>% 
  slice(1:10)
melhores_p12_5
```
```{r SOMENTE UMA MOEDA ESPECIFICA}
MOEDA = 'BTC'

medidas_moeda <- df %>% filter(moeda == MOEDA) %>% 
  group_by(estrategia) %>%
  summarise(
    n = n(),
    min = round(min(lucro, na.rm = TRUE), arredondamento),
    # media = round(mean(lucro, na.rm = TRUE), arredondamento),
    # desv_pad = round(sd(lucro, na.rm = TRUE), arredondamento),
    P12_5 = round(quantile(lucro, probs = 0.125, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    max = round(max(lucro, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>% 
  arrange(-Q1, -mediana) %>% 
  filter(Q1 != mediana & mediana != Q3)
medidas_moeda

p <- ggplot(df %>% filter(moeda == MOEDA & estrategia %in% medidas_moeda$estrategia), 
            aes(x = factor(estrategia, levels = medidas_moeda$estrategia),
                y = lucro,
                fill = factor(estrategia, levels = medidas_moeda$estrategia) ) ) +
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = TRUE, width = 0.5) +
  # Médias extras
  geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "none") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = MOEDA, fill = NULL) +
  coord_flip()
p %>% print()
ggsave(paste0("Estrategias_",MOEDA,".jpg"), height = 40, width = 25, units = "cm", dpi = 600)
```


```{r}
df %>% filter(moeda == 'ONDO' & estrategia == 'KELTNER CHANNEL')
```


```{r Quais algoritmos apresentam mais moedas com lucro maior > 0?}
arredondamento = 1

medidas <- df %>%
  group_by(estrategia, moeda) %>%
  summarise(
    min = round(min(lucro, na.rm = TRUE), arredondamento),
    media = round(mean(lucro, na.rm = TRUE), arredondamento),
    desv_pad = round(sd(lucro, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    max = round(max(lucro, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>%
  mutate(classificacao = ifelse(mediana <= 0, "Negativa", "Positiva") %>% as.factor())

###############################################################################
contagens <- medidas %>%
  group_by(estrategia, classificacao) %>%
  summarise(frequencia = n(), .groups = "drop") %>%
  group_by(estrategia) %>%
  mutate(
    percentual = frequencia / sum(frequencia) * 100
  )

ggplot(contagens, aes(x = as.factor(estrategia), y = percentual, fill = classificacao)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = sprintf("%.0f%%", percentual)),
            position = position_stack(vjust = 0.5),
            color = "black", size = 3.5) +
  coord_flip() +
  labs(x = NULL, y = "Percentual (%)", fill = "Classificação") +
  theme_minimal() +
  theme(legend.position = "bottom")
  theme(legend.position = "bottom")
ggsave("CONTAGEM POSITIVAS POR ESTRATEGIA.jpg", height = 35, width = 15, units = "cm", dpi = 600)

###############################################################################

contagens_moeda <- medidas %>%
  group_by(moeda, classificacao) %>%
  summarise(frequencia = n(), .groups = "drop") %>%
  group_by(moeda) %>%
  mutate(
    percentual = frequencia / sum(frequencia) * 100
  )

ggplot(contagens_moeda, aes(x = as.factor(moeda), y = percentual, fill = classificacao)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = sprintf("%.0f%%", percentual)),
            position = position_stack(vjust = 0.5),
            color = "black", size = 3.5) +
  coord_flip() +
  labs(x = NULL, y = "Percentual (%)", fill = "Classificação") +
  theme_minimal() +
  theme(legend.position = "bottom")
  theme(legend.position = "bottom")
ggsave("CONTAGEM POSITIVAS POR MOEDA.jpg", height = 35, width = 15, units = "cm", dpi = 600)

```


```{r}
df_bck$estrategia %>% as.factor() %>% levels() %>% length()

lista_estrategias = contagens %>% filter(classificacao == 'Positiva' & percentual >= 40)
lista_estrategias = lista_estrategias$estrategia %>% as.factor() %>% levels()
lista_estrategias %>% length()

df = df %>% filter(estrategia %in% lista_estrategias)
```

```{r}
df$estrategia %>% as.factor() %>% levels()
df$moeda %>% as.factor() %>% levels()
```


```{r Analisando distribuição dos lucros/prejuizo}
arredondamento = 1

medidas <- df %>%
  group_by(estrategia, moeda) %>%
  summarise(
    media = round(mean(lucro, na.rm = TRUE), arredondamento),
    mediana = round(median(lucro, na.rm = TRUE), arredondamento),
    Q1 = round(quantile(lucro, probs = 0.25, na.rm = TRUE), arredondamento),
    Q3 = round(quantile(lucro, probs = 0.75, na.rm = TRUE), arredondamento),
    .groups = "drop"
  ) %>%
  mutate(classificacao = ifelse(mediana < 0, "Negativa", "Positiva") %>% as.factor())

df_plot <- df %>%
  left_join(dplyr::select(medidas, estrategia, moeda, classificacao),
            by = c("estrategia", "moeda"))

#------------------------------------------------------------------------------------------------

# p <- ggplot(df_plot %>% filter(estrategia %in% lista_estrategias), 
#             aes(x = as.factor(moeda), y = lucro, fill = classificacao)) + 
#   # Gráficos
#   # geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
#   # geom_boxplot(alpha = 0.8, show.legend = TRUE, width = 0.5) +
#   # Médias extras
#   geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
#   geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
#              shape = 21, fill = "tomato", color = "black", size = 1.5) +
#   geom_point(stat = "summary", fun = "median", show.legend = FALSE,
#              shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
#   # Linha no zero
#   geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
#   geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
#   geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
#   # Estética
#   theme_bw() + theme(legend.position = "bottom") + 
#   labs(x = 'Distribuição dos Lucros', y = NULL, title = NULL, fill = "Classificação") +
#   coord_flip() +
#   facet_wrap(~estrategia, ncol = 5)
# 
# print(p)
# ggsave("analise distribuição - violino.jpg", plot = p, height = lista_estrategias %>% length() * 10, width = 50, units = "cm", dpi = 600)
#########################################################################################################

p <- ggplot(df_plot %>% filter(estrategia %in% lista_estrategias), 
            aes(x = as.factor(moeda), y = lucro, fill = classificacao)) + 
  # Gráficos
  geom_violin(alpha = 0.5, show.legend = TRUE, color = 'white' ) +
  geom_boxplot(alpha = 0.8, show.legend = TRUE, width = 0.5) +
  # Médias extras
  geom_errorbar(stat = "summary", fun.data = "mean_se", width = 0.3, color = "grey60") +
  geom_point(stat = "summary", fun = "mean", show.legend = FALSE,
             shape = 21, fill = "tomato", color = "black", size = 1.5) +
  # geom_point(stat = "summary", fun = "median", show.legend = FALSE,
  #            shape = 21, fill = "#023e8a", color = "black", size = 1.0) +
  # Linha no zero
  geom_hline(yintercept = 0, color = "#880d1e", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 5, color = "#dd2d4a", linetype = "twodash", linewidth = 0.5) +
  geom_hline(yintercept = 10, color = "#f26a8d", linetype = "twodash", linewidth = 0.5) +
  # Estética
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = 'Distribuição dos Lucros', y = NULL, title = NULL, fill = "Classificação") +
  coord_flip() +
  facet_wrap(~estrategia, ncol = 5)

print(p)
ggsave("analise distribuição - boxplot.jpg", plot = p, height = 100, width = 50, units = "cm", dpi = 600)

```


```{r RELAÇÃO LUCRO X PREJUIZO}
library(ggpointdensity)

# ggplot(df, aes(x=valor_lucro_total, y=valor_preuizo_total)) + 
#   geom_hex(bins=17) + 
#   # scale_fill_gradientn(
#   #   colors = c("black", "yellow", "red"),
#   #   values = scales::rescale(c(0, 0.5, 1)),  # define que amarelo está no meio do gradiente
#   #   name = "Contagem"
#   # ) +
#   scale_fill_viridis_c(option = "D") +
#   facet_wrap(~estrategia, ncol = 5) +
#   theme_bw() + theme(legend.position = "bottom")
# ggsave("analise_prejuizo_lucro/1geral.jpg", height = lista_estrategias %>% length() * 2.8, width = 50, units = "cm", dpi = 600)


for (nivel in df$estrategia %>% as.factor() %>% levels()){
  df_filter = df %>% filter(estrategia == nivel)
  maior_valor_eixo = max(max(df_filter$valor_lucro_total, na.rm = TRUE), 
                         -min(df_filter$valor_preuizo_total, na.rm = TRUE))
  
  p = ggplot(df_filter, aes(x=valor_lucro_total, y=valor_preuizo_total)) + 
    geom_hex(bins=17) +
    scale_fill_viridis_c(option = "D") +
    # scale_fill_gradientn(
    #   colors = c("black", "yellow", "red"),
    #   values = scales::rescale(c(0, 0.5, 1)),  # define que amarelo está no meio do gradiente
    #   name = "Contagem"
    # ) +
    theme_bw() + theme(legend.position = "bottom") +
    coord_cartesian(xlim = c(0, maior_valor_eixo), 
                    ylim = c(-maior_valor_eixo, 0))
  p %>% print()
  ggsave(paste0('analise_prejuizo_lucro/',nivel,"point.jpg"), height = 15, width = 15, units = "cm", dpi = 600)
}
```

# ANALISE APROFUNDADA DAS melhores_Q1

```{r}
df_filter = df %>% filter (moeda_estrategia %in% melhores_Q1$moeda_estrategia)
df_filter
```


